language: java
jdk:
  - oraclejdk8

env:
  global:
    - secure: Z8FL3etfRQ4NFozr+q2/3eNhMRFgsgWqEczY4HqvQegOMsQHcTM9L7Lul9zv8LnhQG8MUJaRc977KGLd62Z85A6ugbIpTkiXGfPYugTt/E6//J930OwJg5wCF50OLTiRxKA/SlDr4o7e6+S2roRetGEvT1yYihfHmaTNOlVeyiplxa+Ibn0EnsZrdWAV162Hg6MRSv1m2njZ25i07j04aDaEQg4HO7Te3ElfiSiZUy8OEHT0kGjrVCc521JNUyDk5becG3Fa8fn93rdQlx32AnECylyQTY8ye1EHXUBWDHzVGXo3lm7Vy/1ydVQaqR25rDPOZ4Eu5K/JPkQKzhPfJj1qt7gsj/eBKgSxJNVrB14x9BvTCDuXUGGvUlyzhjd8u/99OjrsyDOD99PTowb8U3JBUxzQNY+dghkWo7ClLgY5+SSCQuL/t1wEdY6Ubew6FsyNY6M1H+G1+Iu00ecJhKT7oPYUfI1TMP7erWqs3H8JF2uEUeXD9yTmw2fejjQ7zQr9uthAgtUtI9xY7CHpAN2kKt/KKowErrPJ2pZ+u2pOAjri/JCynAKlqUBOtgwwimZLwrQmqeeYK5AgJx1o5+qDk31JOPcUvtHg2Fx4XwDlKu7l3aFmOgTCBgMPmqNP9pjHdy6Z0z4EVbtgcANQSnTWfKC7fZb2SviW3sKqH/w=
    - BINTRAY_USER=fabito
